[package]
name = "pinch"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
color-eyre = "*"
chrono = { version = "*", features = ["serde"] }
fs-err = "*"
tracing = "*"
tracing-subscriber = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yml = "*"
xdg = "*"
